# https://ecostack.dev/posts/automated-docker-compose-deployment-github-actions/
name: Docker Image CI

on:
  push:
    branches: [ "develop_cicd" ]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

  deploy:
    runs-on: self-hosted

    steps:

      - name: Add remote server to known_hosts
        run: |
                    ssh-keyscan sfdc_admin@192.168.100.131 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh sfdc_admin@192.168.100.131 << 'EOF'   
            cd /data-storage/sfdc_apps
            docker compose -f 'compose.yaml' -p dev up -d --build
          EOF          
